# Messages

The MessageMedia Messages API provides a number of endpoints for building powerful two-way messaging applications. The Messages API provides access to three main resources:
* Messages - Messages delivered from an application to a handset.
* Delivery Reports - Real time reports on the delivery status of a message. As a message
  is processed, it's status may change several times before it is finally delivered to a handset.
* Replies - Messages sent from a handset to an application. These messages are typically a reply
  to a previously sent message.

![Message Flow](https://i.imgur.com/jJeHwf5.png)

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/11b2a979fa10c6564f77)
