FORMAT: 1A
HOST: https://api.messagemedia.com

In the future this will contain some awesome intro text about MessageMedia, some links out to SDKs and some general onbaording stuff that I'll never have to repeat again. How cool will that be!?

This is where all I'll start with the messaging api spec, and then start including all the other specs... 

<!-- include(../numbers-api-specification/src/external.apib) -->