<!-- include(header.apib) -->

# MessageMedia API Documentation

API spec for the Message Media Platform

Contact: developers@messagemedia.com

Version: <!-- include(version.txt) -->

It is implied that all parameters supplied via url are url encoded

<!-- include(authentication.apib) -->

<!-- include(messaging/messages-external.apib) -->
